# Change the java-maven version as per your development requirements.
FROM maven:3.9.8-eclipse-temurin-22

# Support for adding non-root user during development
RUN usermod -l asura ubuntu

USER asura